// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddcmylbpqyqsenguymbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkY215bGJwcXlxc2VuZ3V5bWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODgxMDgsImV4cCI6MjA2MzQ2NDEwOH0.KO_PEq6bTYhOpdMyJ3VJvXqwL6NEEq1uRJYbOfnVMOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);